/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package polyglot.palindrom

import spock.lang.Specification

class PalindromSpec extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new Palindrom()

        when:
        def result = lib.someLibraryMethod()

        then:
        result == true
    }
}
